### ISSUE TITLE
Documentation for PHP 8 attribute support is missing

### ISSUE THREAD

**Issue by froschdesign** [laminas/laminas-form#122]
Related to #113 

## Tasks

* Create new page with description for attributes
* Extract description for annotations from Quick Start to own page

## Page Structure

* Introduction
* Installation requirements (doctrine/annotations)
* Basic usage with code example (form, builder)
* all annotations / attributes with separate code example

**Comment by Slamdunk** [comment]
@driehle could you have a try on this task?

**Comment by driehle** [comment]
Yes, but I think that will require restructuring the documentation. Currently, annotation is only mentioned in the quick start tutorial. I would suggest to introduce a new section:

- Introduction
- Installation
- Quick start
- Form creation
  - Creation via factory
  - Factory-based form extension
  - Annotations and attributes
- Application integration
  - Usage in Laminas MVC
- Reference

Quick start would then only have the programmatic form creation. Alternatively, that could be moved to the new section as well with links in the quick start page. What do you think?

**Comment by froschdesign** [comment]
@driehle 
> Quick start would then only have the programmatic form creation.

This all is correct, but I did not want to make this issue report any bigger.
There is enough to do:

> all annotations / attributes with separate code example
