### ISSUE TITLE
Problems in tests with collections and setValidationGroup()

### ISSUE THREAD

**Issue by froschdesign** [laminas/laminas-form#174]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.2.0

#### Summary

Two problems with the release of 3.2.0 that were hidden in the pull requests:

```
LaminasTest\Form\FormTest::testSetValidationGroupOnFormWithNestedCollectionsRaisesInvalidArgumentException
Laminas\InputFilter\Exception\InvalidArgumentException: setValidationGroup() expects a list of valid input names; "0" was not found
```

https://github.com/laminas/laminas-form/runs/6916463844?check_suite_focus=true#step:3:447

```
LaminasTest\Form\FormTest::testSetValidationGroupOnFormWithNestedCollectionsPopulatesOnlyFirstNestedCollectionElement
Laminas\InputFilter\Exception\InvalidArgumentException: setValidationGroup() expects a list of valid input names; "0" was not found
```

https://github.com/laminas/laminas-form/runs/6916463844?check_suite_focus=true#step:3:460

**Comment by Slamdunk** [comment]
> hidden in the pull requests

:open_mouth:

**Comment by froschdesign** [comment]
Interesting, because the problem appears in my fork, but not here: https://github.com/froschdesign/laminas-form/actions/runs/2500515004

**Comment by froschdesign** [comment]
The problem is gone.
