### ISSUE TITLE
FormAttributeBuilder exception break on php 7.4

### ISSUE THREAD

**Issue by wiryonolau** [laminas/laminas-form#176]
### BC Break Report

|    Q        |   A
|------------ | ------
| Version     | ^3

#### Summary

Annotation\AttributeBuilder::class thrown Exception on php7 when loading from factory
while composer.json  still allow to use it in php7

**Comment by Ocramius** [comment]
@wiryonolau could you provide more details? What is happening exactly?

**Comment by wiryonolau** [comment]
Hi we use this individually. Most of our project are still in 7.4. We using PHP-DI to load all dependency
before we only load view_helpers, so everything is normal.

We just start implement loading abstract factory similar to servicemanager
On loading the dependency it break on AttributeBuilder::__construct() since it always requested PHP8

**Comment by Ocramius** [comment]
Yes, but what is the exception (with trace), and what is the code (on your end) causing it?

**Comment by wiryonolau** [comment]
On unittest only this error
PHP 8.0 or newer is required when using PHP attributes. You are running PHP 7.4.29.
Undefined index: FormAttributeBuilder

ERROR : 
No entry or class found for 'FormAttributeBuilder' ( this is from PHP-DI )

**Comment by Ocramius** [comment]
Seems like you may want to report this on PHP-DI then, since the attributes are not used in this component, unless you explicitly use an attribute builder.

Closing here, since it's not a bug of `laminas/laminas-form`

**Comment by wiryonolau** [comment]
Does __construct() not called by servicemanager ?

**Comment by wiryonolau** [comment]
```php
# ConfigProvider.php

<?php
public function getDependencyConfig(): array
    {
        return [
            'abstract_factories' => [
                FormAbstractServiceFactory::class,
            ],
            'aliases'            => [
                Annotation\AnnotationBuilder::class => 'FormAnnotationBuilder',
                Annotation\AttributeBuilder::class  => 'FormAttributeBuilder',
                FormElementManager::class           => 'FormElementManager',
            ],
            'factories'          => [
                'FormAnnotationBuilder' => Annotation\BuilderAbstractFactory::class,
                'FormAttributeBuilder'  => Annotation\BuilderAbstractFactory::class,
                'FormElementManager'    => FormElementManagerFactory::class,
            ],
        ];
    }
```

FormAttributeBuilder never get called in here ?

**Comment by Ocramius** [comment]
It gets fetched (via factory) if you want to use it directly - you'd still need to get it from a configured servicemanager.

**Comment by wiryonolau** [comment]
Ok my problem is in my unittest, cause I checking all registered service for any error or circular dependency. Guess the FormAttributeBuilder get called by it.

Wish they create a specific Exception for detecting PHP Version 8, instead of just throwing a generic Exception
