### ISSUE TITLE
Github pages isn't working(

### ISSUE THREAD

**Issue by GR4NDS0N162** [laminas/laminas-form#178]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | x.y.z

**Comment by Ocramius** [comment]
~~@Slamdunk do you know if `gh-pages` got deleted by accident here?~~

EDIT: nvm, found that @internalsystemerror fat-fingered this (event 22918984497)

**Comment by Ocramius** [comment]
Re-triggered https://github.com/laminas/laminas-form/actions/runs/2568694836 meanwhile

**Comment by Ocramius** [comment]
@froschdesign that CI job I just linked can't run because `gh-pages` is missing: do you know if creating an empty `gh-pages` branch would suffice? I don't have a working copy of `laminas-form`, so I can't restore it from my end.

**Comment by weierophinney** [comment]
Let me know if you want help.

Generally speaking, you should be able to create an empty branch, and then re-trigger the docs-build action. If that doesn't work, we can build using the container; the only issue I've had with that is that the code example styles get all fubar.

**Comment by Ocramius** [comment]
Pushed an old version of `gh-pages` for now, provided by @internalsystemerror: d84f5c4210c717b08c2c63f2a86eb26d60a5a501

Will re-trigger build now.

**Comment by Ocramius** [comment]
Restored: https://docs.laminas.dev/laminas-form/

**Comment by internalsystemerror** [comment]
Sorry all ... My bad ...
