### ISSUE TITLE
add minlength as valid attribute for textarea

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-form#2]
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-minlength) web docs and [WHATWG HTML Living Standard](https://html.spec.whatwg.org/multipage/input.html#the-maxlength-and-minlength-attributes), the `minlength` attribute also apply to `textarea` form elements.

other form elements that applied `minlength` already included by https://github.com/zendframework/zend-form/issues/206

---

Originally posted by @habibillah at https://github.com/zendframework/zend-form/pull/231

**Comment by weierophinney** [comment]
We should add this change to Changelog file.

---

Originally posted by @dennybrandes at https://github.com/zendframework/zend-form/pull/231#issuecomment-561717170

**Comment by samsonasik** [comment]
I created PR #69 for it.
