### ISSUE TITLE
Add onfocusout on $validGlobalAttributes

### ISSUE THREAD

**Issue by Milooz** [laminas/laminas-form#201]
### Feature Request

Hello,
on laminas-form, is it possible to add 'onfocusout' attribute  in the $validGlobalAttributes Array in the file :
\laminas\laminas-form\src\View\Helper\AbstractHelper.php

**Comment by froschdesign** [comment]
@Milooz 
Can you create a pull request for your feature request?
Add `onfocusout` and `onfocusin` with the related links to HTML specs, like the other attributes:

https://github.com/laminas/laminas-form/blob/a668218bf3d1545e2f276bc17146ee6b29debe5c/src/View/Helper/AbstractHelper.php#L133

The new attributes should also be covered in the [tests](https://github.com/laminas/laminas-form/blob/a668218bf3d1545e2f276bc17146ee6b29debe5c/test/View/Helper/FormInputTest.php#L100).

Thanks in advance! 👍🏻
