### ISSUE TITLE
Can't require latest package version when using PHP 8.0 running composer

### ISSUE THREAD

**Issue by FabianRahm** [laminas/laminas-form#215]
### BC Break Report

|    Q        |   A
|------------ | ------
| Version     | latest via composer

#### Summary

While trying to update all my laminas packages before enabling PHP 8.1, I can't upgrade to the lastest laminas-form package. Most other laminas packages have a different PHP version requirement (e.g. ~8.0.0 || ~8.1.0 || ~8.2.0)

laminas/laminas-form 3.10.1 requires php ~8.1.0 || ~8.2.0 -> your php version (8.0.28) does not satisfy that requirement.

#### Previous behavior

Expected to be PHP 8.0 compatible

#### Current behavior

Can't require the latest package with PHP 8.0

#### How to reproduce

php8.0 composer require laminas/laminas-form

**Comment by Slamdunk** [comment]
This is intended (https://github.com/laminas/laminas-form/pull/208) as Active Support for PHP 8.0 ended 5 months ago.

**Comment by FabianRahm** [comment]
Thank you. Can I find a lifecycle roadmap for all components somewhere?

**Comment by Ocramius** [comment]
We bump the **latest** version to a component to any PHP version that we consider worth bumping to.
We maintain bug fixes for those latest versions.
We maintain security for components up until the base PHP version that they support goes EOL.

Ref: https://github.com/laminas/technical-steering-committee/blob/7c459744232c9aab08710d26ff56a7666a1e5cf4/meetings/minutes/2020-03-02-TSC-Minutes.md#lts-policy

**Comment by FabianRahm** [comment]
Thanks @Ocramius - all upgraded to the latest versions now.
