### ISSUE TITLE
Bug of day 31 (Element\Month)

### ISSUE THREAD

**Issue by samuelgmartins** [laminas/laminas-form#217]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | any

#### Summary

When using a month element with the server date May 31st for example, the default validation of the DateStep returns false when selecting a month with less than 31 days.

#### Current behavior

"The input is not a valid step"

#### How to reproduce

Adjust the date to 2023-05-31

```php
use Laminas\Form\Form;
use Laminas\Form\Element;

$form = new Form();
$mesAnoIni = new Element\Month('mes_ano_inicio');
$form->add($mesAnoIni);
$form->setData(['mes_ano_inicio' => '2023-02']);
// $mesAnoIni->setAttribute('step', 'any'); // temporary fix
var_dump($form->isValid()); // return false
```

#### Expected behavior

Date validated regardless of the day on the server

#### How to permanently fix

[https://www.php.net/manual/en/datetimeimmutable.createfromformat.php] datetimeimmutable.createfromformat.php

All fields are initialized with the current date/time. In that case, you'll want to reset them to "zero". You do this by including the ! character as the first character in your format, or | as your last.

[src/Element/Month.php](https://github.com/laminas/laminas-form/blob/3.11.x/src/Element/Month.php)
```php
...
class Month extends AbstractDateTime
{
    /**
     * A valid format string accepted by date()
     *
     * @var string
     */
    protected $format = '!Y-m';`
```

**Comment by Ocramius** [comment]
Would it be possible to have a failing test for this?

**Comment by samuelgmartins** [comment]
> Would it be possible to have a failing test for this?

Need to adjust the server date, because otherwise the test would work on most days except the 31st or 30th when selected February

**Comment by Ocramius** [comment]
I see: perhaps a test that verifies the internally created date object would help though 🤔

**Comment by Slamdunk** [comment]
> because otherwise the test would work on most days except the 31st or 30th when selected February

The exclamation mark also resets the time part of the date, so a test asserting `->format('d H:i:s')` is always `01 00:00:00` would be resilient enough
