### ISSUE TITLE
DateTime related elements should accept DateTimeInterface values

### ISSUE THREAD

**Issue by pine3ree** [laminas/laminas-form#224]
### Feature Request

The elements of type `MonthSelect`, `DateSelect` and `DateTimeSelect` do not accept `DateTimeImmutable` instances, only `DateTime`. They should accept `DateTimeInterface` (e.g. https://github.com/laminas/laminas-form/blob/193b2e5f2a5a297b975ef38700c7d3742abab1a2/src/Element/MonthSelect.php#L271)

**Comment by Ocramius** [comment]
I think these were written way before PHP 5.4: possibly worth sending a
patch :-)
Marco Pivetta

***@***.***

https://ocramius.github.io/
