### ISSUE TITLE
Date pattern parsing fails with "exotic" locales

### ISSUE THREAD

**Issue by pine3ree** [laminas/laminas-form#228]
The `AbstractFormDateSelect::parsePattern()` method
https://github.com/laminas/laminas-form/blob/a41bb38a759590141e14fe907c107f80c7c3569b/src/View/Helper/AbstractFormDateSelect.php#L74

seems unable to handle less common locales.
Added a failing test with `zh_Hans_HK` locale. In this case the `month` part is not extracted (https://github.com/laminas/laminas-form/pull/229)

**Comment by Slamdunk** [comment]
Thank you for bringing this up.

So the `IntlDateFormatter::LONG` pattern for `zh_Hans_HK` seems to be `y年M月d日 z ah:mm:ss`.

Then the `FormDateTimeSelect` tries to split that pattern here:

https://github.com/laminas/laminas-form/blob/abc710a89cf57b187f9e71e45912ebba2afdff63/src/View/Helper/FormDateTimeSelect.php#L197-L202

The last `([ \-,.:\/]+)` is what we need to focus on: it considers few basic chars as the split sequence, but not those chinese  chars inside `y年M月d日`.

We could try to fix this by replacing any non-ASCII char with a space, so the `preg_split` behaves as expected again, what do you think?

**Comment by pine3ree** [comment]
Hello @Slamdunk  ,

I believe that those non-ASCII characters (mostly present in asian languages, I remember Japanese uses them `kanji`  too) are meaningful delimiters and they should be captured as such (like the ` 'at' ` delimiter for `en_US`) so that are displayed later on before/after the corresponding "select" element. 
They usually mean "day", "month", "year",...and so on. I am not sure that simply surrounding them with single quotes before parsing will work. 
Different locale also use them differently:
- `zh_*` locales use pictograms down to `IntlDateFormatter::MEDIUM`
-  `ja_*` locales use pictograms down to `IntlDateFormatter::FULL`

Anyway, we should either (1) add tests and make the helpers work for all supported locales, or (2) limit the supported locales and add a generic simple alternative for those we do not (won't or can't) support. 

kind regards

PS
I guess that after JavaScript selectors appeared many years ago, very few developers are nowadays using "select" element groups for "datetime" related inputs.

**Comment by Slamdunk** [comment]
> (2) limit the supported locales and add a generic simple alternative for those we do not (won't or can't) support.

That sounds fair enough to me: would you like to propose such change?

**Comment by pine3ree** [comment]
PS
As a quick fix (what I added in my plates functions for laminas-form)
```php
        if (!isset($result['month'])) {
            $result['month'] = 'M';
        }
``` 
and similar for other missed captures

(edit) not related to your answer, I saw it after posting

**Comment by pine3ree** [comment]
btw, this string, wrapping pictograms inside single quotes, `y'年'M'月'd'日' z ah:mm:ss` is parsed correctly

**Comment by pine3ree** [comment]
List of patterns by locale that result one of the following keys missing: year,month,day,hour,minute):
```
          bo => སྤྱི་ལོ་y MMMMའི་ཚེས་d HH:mm:ss
       bo_CN => སྤྱི་ལོ་y MMMMའི་ཚེས་d HH:mm:ss
       bo_IN => སྤྱི་ལོ་y MMMMའི་ཚེས་d h:mm:ss a
          ja => y年M月d日 H:mm:ss
       ja_JP => y年M月d日 H:mm:ss
         yue => y年M月d日 ah:mm:ss [z]
    yue_Hans => y年M月d日 z HH:mm:ss
 yue_Hans_CN => y年M月d日 z HH:mm:ss
    yue_Hant => y年M月d日 ah:mm:ss [z]
 yue_Hant_HK => y年M月d日 ah:mm:ss [z]
          zh => y年M月d日 z HH:mm:ss
     zh_Hans => y年M月d日 z HH:mm:ss
  zh_Hans_CN => y年M月d日 z HH:mm:ss
  zh_Hans_HK => y年M月d日 z ah:mm:ss
  zh_Hans_MO => y年M月d日 z ah:mm:ss
  zh_Hans_SG => y年M月d日 z ah:mm:ss
     zh_Hant => y年M月d日 Bh:mm:ss [z]
  zh_Hant_HK => y年M月d日 ah:mm:ss [z]
  zh_Hant_MO => y年M月d日 ah:mm:ss [z]
  zh_Hant_TW => y年M月d日 Bh:mm:ss [z]

```
SO we basically hav 2 unhandled expressions `སྤྱི་ལོ་y MMMMའི་ཚེས་d` and `y年M月d日` (they are the same for LONG and MEDIUM formats, the list is using the LONG format)

**Comment by pine3ree** [comment]
For the `datetime-select` I believe a the following change in regex should work:

```php
<?php

const PATTERN_REGEX   = "/([ \-,.:\/]*'.*?'[ \-,.:\/]*)|([ \-,.:\/]+)/"; // original pattern
const PATTERN_REGEX_U = "/([ \-,.:\/]*'.*?'[ \-,.:\/]*)|([ \-,.:\/]+)|([^[:ascii:]]+)/u";


function getPattern(string $locale): string {
    $intl = new IntlDateFormatter($locale, IntlDateFormatter::LONG,IntlDateFormatter::LONG);

    $pattern = $intl->getPattern();
    $pattern = str_replace([' z ' , '(z)', '[z]', ' z'], '', $pattern);
    $pattern = preg_replace('/\s+/', ' ', $pattern);
    $pattern = trim($pattern);

    return $pattern;
}

function parsePattern(string $pattern, bool $renderDelimiters = true): array {

    $pregResult = preg_split(
        PATTERN_REGEX_U,
        $pattern,
        -1,
        PREG_SPLIT_DELIM_CAPTURE | PREG_SPLIT_NO_EMPTY
    );

    $result = [];
    foreach ($pregResult as $value) {
        $noDelimiter = stripos($value, "'") === false;
        if ($noDelimiter && stripos($value, 'd') !== false) {
            $result['day'] = $value;
        } elseif ($noDelimiter && str_contains($value, 'M')) {
            $result['month'] = $value;
        } elseif ($noDelimiter && stripos($value, 'y') !== false) {
            $result['year'] = $value;
        } elseif ($noDelimiter && stripos($value, 'h') !== false) {
            $result['hour'] = $value;
        } elseif ($noDelimiter && stripos($value, 'm') !== false) {
            $result['minute'] = $value;
        } elseif ($noDelimiter && str_contains($value, 's')) {
            $result['second'] = $value;
        } elseif ($noDelimiter && stripos($value, 'a') !== false) {
            // ignore ante/post meridiem marker
            continue;
        } elseif ($renderDelimiters) {
            $result[] = str_replace("'", '', $value);
        }
    }

    return $result;
}

Locale::setDefault('en_US');

echo "\n";

foreach (IntlCalendar::getAvailableLocales() as $locale) {

    $pattern = getPattern($locale);
    $result  = parsePattern($pattern);

    echo sprintf("%s => %s\n", $locale, $pattern);
    echo sprintf("%s => %s\n", $locale, json_encode($result, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_LINE_TERMINATORS));
    echo "\n";
}
```

There were also leftover timezone symbols in different forms, and strangely, a couple of inner newlines (taken care in `getPattern`)

**Comment by pine3ree** [comment]
Regarding the date-only-select, using this modified pattern
```php
"/([ \-,.\/]*(?:'[a-zA-Z]+')*[ \-,.\/]+)|([^[:ascii:]]+)/u";
```
 we can extract year, month, day excluding the following related edge cases (Basque):
```
eu => y('e')'ko' MMMM'ren' d('a')
eu => {"0":"y(e)","1":"ko ","month":"MMMM","2":"ren ","3":"d(a)"}

eu_ES => y('e')'ko' MMMM'ren' d('a')
eu_ES => {"0":"y(e)","1":"ko ","month":"MMMM","2":"ren ","3":"d(a)"}
```

**Comment by pine3ree** [comment]
This seems to work with all dates:
```php
$dateSplitRegex = "/([ \-,.\/]*(?:\('[a-zA-Z]+'\))*(?:'[a-zA-Z]+')*[ \-,.\/]+)|([^[:ascii:]]+)*(?:\('[a-zA-Z]+'\))*(?:'[a-zA-Z]+')*/u";
```

**Comment by pine3ree** [comment]
Premise: I deleted all previous comments, since I believe to have found a simpler generic regular common expression for splitting the intl date-time pattern, in expanded format:

```php
const SPLIT_REGEX = <<<EOR
    /
        (
            [^a-z']*
            (?:
                \('[^']+'\)
                |
                '[^']+'
                |
                [^a-z']+
            )+
            [^a-z']*
        )+
    /xiu
    EOR;
```

together with the modified method:
```php
function getPattern(string $locale, IntlDateFormatter $intl = null): string
{
    $intl = new IntlDateFormatter($this->getLocale(), $this->dateType, $this->timeType);

    $pattern = $intl->getPattern();
    // Remove time zone format character present in various forms
    $pattern = str_replace(['(z)', '[z]', 'z ', ' z ' , ' z'], ' ', $pattern);
    // Remove time meridiem character present in various forms
    $pattern = str_replace(['(a)', '[a]', ' a ' , 'a ', ' a'], ' ', $pattern);
    // Cleanup extra inner spaces
    $pattern = preg_replace('/\s+/', ' ', $pattern);
    // Remove trailing commas from previous operations
    $pattern = trim($pattern, ", \t\n\r\0\x0B");

    return $pattern;
}
```

The regex works like this:

ref: https://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table
ref: https://unicode-org.github.io/icu/userguide/format_parse/datetime/#date-field-symbol-table

the splitting string may have:
- OPTIONAL PREFIX: non alfabetic-ascii chars (alfas not wrapped in single quotes are only used for date-time output, see tables)
- EITHER
  - an escaped string wrapped in parenthesis `('a')` , `('e')`
  - an escaped unwrapped string `'at'`
  - one or more non alfabetic-ascii chars
- OPTIONAL SUFFIX: non alfabetic-ascii chars (alfas not wrapped in single quotes are only used for date-time output, see tables)

non alfabetic-ascii chars include standard date time separators like `/`, `-`, `:`, etc and all unicode symbols for year, month, day etc

result: https://onlinephp.io/c/97ff2
