### ISSUE TITLE
[RFC] Improve type inference for `getData()`

### ISSUE THREAD

**Issue by gsteel** [laminas/laminas-form#238]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

With https://github.com/laminas/laminas-inputfilter/pull/91 landing in input-filter, it'll be easier to annotate forms with something like:

```php
/**
 * @psalm-type ValidPayload = array{
 *     field1: int<1, 365>,
 *     field2: non-empty-string,
 *     field3: list<non-empty-string>,
 * }
 * @extends Form<ValidPayload>
 */
final class MyForm extends Form
{
}
```

It's been a while since I used form for anything other than regular associative arrays, but given forms can be bound to objects too - it's also feasible that forms could be annotated to return models too, such as:

```php
/** @extends Form<SomeModel> */
final class MyForm extends Form
{
}
```

The patch in InputFilter helps because users will be able to do something like the following:

```php
/**
 * @psalm-import-type ValidPayload from MyInputFilter
 * @extends Form<ValidPayload>
 */
final class MyForm extends Form
{
    public function __construct(MyInputFilter $inputFilter)
    {
        parent::__construct();
        $this->setInputFilter($inputFilter);
    }
}
```

**Comment by Ocramius** [comment]
> `/** @extends Form<SomeModel> */`

Very cool and elegant 💪

**Comment by gsteel** [comment]
Hopefully the psalm bot is working here. This is what I have in mind:

https://psalm.dev/r/0d6f0ee752
