### ISSUE TITLE
Problem with different Renderer

### ISSUE THREAD

**Issue by netzfische** [laminas/laminas-form#249]
I'm using a Smarty-Renderer which implements the RendererInterface but does not extend the PhpRenderer.

So the following line fails for me:
https://github.com/laminas/laminas-form/blob/2ec86da41462b8f9445b3d5f5ab4c5fc829d30f4/src/View/Helper/FormElement.php#L166

Would it be possible to change this to:
`assert($renderer instanceof RendererInterface);`

**Comment by Xerkus** [comment]
Not really. Form view helpers depend on helper plugin manager which is part of php renderer and not renderer interface.

**Comment by netzfische** [comment]
Thanks for the quick info. 
I will adjust my Renderer in this case.

**Comment by froschdesign** [comment]
@netzfische 
> I'm using a Smarty-Renderer…

Is this a public project or is there a repository for this?

**Comment by devlubinets** [comment]
@netzfische is it closed?

**Comment by netzfische** [comment]
Yes, I solved it in the smarty module.

**Comment by netzfische** [comment]
Thanks
