### ISSUE TITLE
Zend\Form\Element\Select default InArray validation broken

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-form#39]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

---

Original Issue: https://api.github.com/repos/zendframework/zendframework/issues/7586
User: @phpManiac77
Created On: 2015-06-15T16:17:13Z
Updated At: 2015-12-09T20:53:03Z
Body
Default in array validation does not work any more.

In method Zend\Form\Element\Select::setValueOptions() on line 80 $this->validator is checked against ! null. This is always false because $this->validator is nowhere set. 

---
### Comment

User: @demichl68
Created On: 2015-12-09T20:53:03Z
Updated At: 2015-12-09T20:53:03Z
Body
As soon as `getValidator()` is called, `$validator` is not null anymore.
`getValidator()` is called when `getInputSpecification()` is called.

---

---

Originally posted by @GeeH at https://github.com/zendframework/zend-form/issues/89

**Comment by froschdesign** [comment]
The element works as expected:

```php
$form          = new Laminas\Form\Form();
$selectElement = new Laminas\Form\Element\Select();
$selectElement->setName('my-select');
$selectElement->setValueOptions(['Foo', 'Bar']);
$form->add($selectElement);

var_dump($selectElement->getValueOptions());
var_dump($selectElement->getInputSpecification()['validators'][0]->getHaystack());

$form->setData(['my-select' => 2]);
var_dump($form->isValid());
var_dump($form->getMessages());

$form->setData(['my-select' => 0]);
var_dump($form->isValid());
```
Output:
```php
array(2) {
  [0]=>
  string(3) "Foo"
  [1]=>
  string(3) "Bar"
}
array(2) {
  [0]=>
  int(0)
  [1]=>
  int(1)
}
bool(false)
array(1) {
  ["my-select"]=>
  array(1) {
    ["notInArray"]=>
    string(39) "The input was not found in the haystack"
  }
}
bool(true)
```
