### ISSUE TITLE
Form implements InputFilterProviderInterface - validators fix

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-form#44]
When Form implements `InputFilterProviderInterface` and validators for an element are defined in method `getInputFilterSpecification`, only these validators should be added to the `InputFilter` of the Form for the element.
The same behavior should be for Fieldsets and it works fine. Basically, validators defined in `getInputFilterSpecification` should override default validators of the Element.

---

Originally posted by @michalbundyra at https://github.com/zendframework/zend-form/pull/82

**Comment by michalbundyra** [comment]
Does this fix mean, that I have to copy all filters from method `getInputSpecification` of elements like (Email, Number) or my custom element and paste it to `getInputFilterSpecification` just to set field 'required' => false ??? 
Does it make sense?


---

Originally posted by @megapixar at https://github.com/zendframework/zend-form/pull/82#issuecomment-235281599

**Comment by michalbundyra** [comment]
@akrabat Could you have a look on it, please?

---

Originally posted by @michalbundyra at https://github.com/zendframework/zend-form/pull/82#issuecomment-281956659

**Comment by michalbundyra** [comment]
@froschdesign @akrabat rebased

---

Originally posted by @michalbundyra at https://github.com/zendframework/zend-form/pull/82#issuecomment-281968051

**Comment by michalbundyra** [comment]
Is this a BC break?

---

Originally posted by @akrabat at https://github.com/zendframework/zend-form/pull/82#issuecomment-281976146

**Comment by michalbundyra** [comment]
i.e. if I add an email element and specify an additional validator that the length must be greater than 5, does this PR mean that the EmailAddress validator is no longer added?

---

Originally posted by @akrabat at https://github.com/zendframework/zend-form/pull/82#issuecomment-281976385

**Comment by michalbundyra** [comment]
@akrabat I've created an example here: https://gist.github.com/webimpress/e08e5a8928cbc3fec249fdc723705652

So, __without__ my fix we have got:
```
NUMBER OF VALIDATORS:
field   form    fieldset
email   2       1
custom  2       1
```

and **with** my fix we have:
```
NUMBER OF VALIDATORS:
field   form    fieldset
email   1       1
custom  1       1
```

Basically there is something wrong. I've decided to do this way, so override default validators. In my application always I'm using fieldset and always when I get field from fieldset (from a form) validators specified in `getInputFilterSpecification` are only used.

Please note, I haven't changed any tests, so I haven't break (tested) functionality. IMHO if you implement form with `InputFilterProviderInterface` then you want specify input filter rules **in the form**, so only these should be used.

---

Originally posted by @michalbundyra at https://github.com/zendframework/zend-form/pull/82#issuecomment-281989202

**Comment by michalbundyra** [comment]
This repository has been moved to laminas/laminas-form. If you feel that this patch is still relevant, please re-open against that repository, and reference this issue. To re-open, we suggest the following workflow:
 - Squash all commits in your branch (`git rebase -i origin/{branch}`)
 - Make a note of all changed files (`git diff --name-only origin/{branch}...HEAD
 - Run the laminas/laminas-migration tool on the code.
 - Clone laminas/laminas-form to another directory.
 - Copy the files from the second bullet point to the clone of laminas/laminas-form.
 - In your clone of laminas/laminas-form, commit the files, push to your fork, and open the new PR.
 We will be providing tooling via laminas/laminas-migration soon to help  automate the process.

---

Originally posted by @weierophinney at https://github.com/zendframework/zend-form/pull/82#issuecomment-570002309

**Comment by Slamdunk** [comment]
@froschdesign I understand the motivation for https://github.com/zendframework/zend-form/pull/82 but I do not agree that's a good solution.
Most common usage I know consists of implementing `getInputFilterSpecification` just to add `'required' => true` and `StringTrim` filter, it would be tedious and error prone to repeat default validators just for a `'required' => true`.

So I'm inclined to close this as `Won't fix`; WDYT?

**Comment by froschdesign** [comment]
> So I'm inclined to close this as `Won't fix`; WDYT?

Go for it. The way is always open to create a new issue report.
