### ISSUE TITLE
Missing dependency to zend-servicemanager ?

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-form#46]
Hi,

I'm using zend-form as a standalone library (in a Symfony2 project), and I realize that since [this commit](https://github.com/zendframework/zend-form/commit/12caaebd4a5ea16cd17aca9b754dc20d1331fcd4) (introduced in v2.8.2) there is a [new autoload file](https://github.com/zendframework/zend-form/blob/12caaebd4a5ea16cd17aca9b754dc20d1331fcd4/autoload/formElementManagerPolyfill.php) which creates an alias `FormElementManager` for either `FormElementManagerV3Polyfill` or `FormElementManagerV2Polyfill` (the latter in my case).

So here's my problem : when I run a `composer update` the `Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap` post-update command fails with this error :

```
PHP Fatal error:  Class 'Zend\ServiceManager\AbstractPluginManager' not found in /sites/sfwebfstore/vendor/zendframework/zend-form/src/FormElementManager/FormElementManagerV2Polyfill.php on line 28
```

Actually the command doesn't matter, the problem appears very soon during the autoload phase.

I suspect this error to be a consequence of the absence of zend-servicemanager as a non-dev dependency in the composer.json of this project.
Indeed, considering I'm using zend-form in standalone and that zend-servicemanager isn't a dependency of any of the others packages, `Zend\ServiceManager\AbstractPluginManager` doesn't exists and an error appears.

I don't know if it makes sense to set zend-servicemanager as a non-dev requirement in this project, but I think it would resolve this problem (I'm not sure).
If you think it's not a good idea, please help me to find a solution because I'm pretty stucked there :-)

---

Originally posted by @chapa at https://github.com/zendframework/zend-form/issues/72

**Comment by michalbundyra** [comment]
I have had the same issue while installing zend-form with zend-expressive (fastroute+pimple+plates).
Even just requiring zend-form (`composer require zendframework/zend-form`) and including the generated `vendor/autoload.php` will cause the issue. The zend-form composer.json require a file:
`autload/formElementManagerPolyfill.php` which defines a class alias for FormElementManager based on the service manager version. Confirming the version as well: zend-form v 2.8.1 is not affected.


---

Originally posted by @pine3ree at https://github.com/zendframework/zend-form/issues/72#issuecomment-220270329

**Comment by michalbundyra** [comment]
zend-form 2.10 is affected. This is bad, because my app crashes directly after autoloading.

---

Originally posted by @mreiche at https://github.com/zendframework/zend-form/issues/72#issuecomment-315721798

**Comment by michalbundyra** [comment]
confirm the problem :(

---

Originally posted by @antgubarev at https://github.com/zendframework/zend-form/issues/72#issuecomment-331696259

**Comment by michalbundyra** [comment]
@pine3ree is right, the polyfill and autoloading is the problem.


---

Originally posted by @froschdesign at https://github.com/zendframework/zend-form/issues/72#issuecomment-332737779

**Comment by michalbundyra** [comment]
Will this be fixed, as far as I can see this problem still persists?

---

Originally posted by @ikdekker at https://github.com/zendframework/zend-form/issues/72#issuecomment-405174435

**Comment by michalbundyra** [comment]
@ikdekker send a patch: nothing fixes itself in OSS :-)

---

Originally posted by @Ocramius at https://github.com/zendframework/zend-form/issues/72#issuecomment-405176367

**Comment by froschdesign** [comment]
The autoload file was removed with [version 2.16.0](https://github.com/laminas/laminas-form/releases/tag/2.16.0) (#75).
