### ISSUE TITLE
Form annotations don't work on PHP 7

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-form#48]
I've narrowed the problem down the the Zend-code dependency. I don't know if there is any way we can fix this for PHP 7; perhaps a documentation update warning of this fact. ~~The fix I assume is going to be to upgrade to Zend-code 3 which has PHP 7 support.~~ Turns out even Zend code 3.0.0 isn't sufficient

---

Originally posted by @carnage at https://github.com/zendframework/zend-form/issues/51

**Comment by michalbundyra** [comment]
Related:
- https://github.com/zendframework/zend-code/issues/49
- https://bugs.php.net/bug.php?id=71914


---

Originally posted by @Ocramius at https://github.com/zendframework/zend-form/issues/51#issuecomment-207077135

**Comment by michalbundyra** [comment]
What's your opinion on switching to use doctrines annotation parser anyway as it's better than the Zend one? Plus it would remove the dependency on Zend code from the form module.


---

Originally posted by @carnage at https://github.com/zendframework/zend-form/issues/51#issuecomment-207084698

**Comment by michalbundyra** [comment]
@carnage We already delegate to Doctrine's annotation parser; all our code does is get the raw annotations and pass them to that. (zend-code provides the reflection functionality for retrieving the annotations, which is not something we want to duplicate here.)


---

Originally posted by @weierophinney at https://github.com/zendframework/zend-form/issues/51#issuecomment-215542597

**Comment by michalbundyra** [comment]
Doctrine's annotation parser is already capable of getting the raw annotations and does it correctly in PHP 7. We are only using Zend code here to parse the file which isn't required for our use case here as we only need the doc blocks.


---

Originally posted by @carnage at https://github.com/zendframework/zend-form/issues/51#issuecomment-215656884

**Comment by michalbundyra** [comment]
any news on this?


---

Originally posted by @lowtower at https://github.com/zendframework/zend-form/issues/51#issuecomment-247941978

**Comment by michalbundyra** [comment]
Seems the problem only exists on PHP 7.0.5 a newer version should work otherwise there is a WIP pull request which fixes the issue: you could use my fork/patch or finish off the fix and make a proper PR with it.

Ideally, a refactor which removes the Zend code dependency would be the best option.


---

Originally posted by @carnage at https://github.com/zendframework/zend-form/issues/51#issuecomment-247945794

**Comment by michalbundyra** [comment]
Thanks for Your quick reply!
Using exactly PHP 7.0.5 on my shared host :-(
Will be using Your fork.
Thanks,
LT.


---

Originally posted by @lowtower at https://github.com/zendframework/zend-form/issues/51#issuecomment-247951718

**Comment by michalbundyra** [comment]
Might I suggest, for stability purposes, you make your own fork of my patch and use that.


---

Originally posted by @carnage at https://github.com/zendframework/zend-form/issues/51#issuecomment-247952139

**Comment by michalbundyra** [comment]
Yes, thanks for the suggestion


---

Originally posted by @lowtower at https://github.com/zendframework/zend-form/issues/51#issuecomment-247952315

**Comment by driehle** [comment]
@Slamdunk I guess this can be closed as well now

**Comment by Slamdunk** [comment]
This may be closed by #113, feel free to reopen it if new evidences emerge.
