### ISSUE TITLE
FormRow: allow attributes for "valid" context

### ISSUE THREAD

**Issue by Slamdunk** [laminas/laminas-form#63]
|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | maybe

Hi, FormRow view helper generates two outputs:

1. Element without errors
1. Element with errors

This schema lacks a third option, hidden in the first one; the outputs should be:

1. Element rendered, waiting to be filled
1. Element filled without errors
1. Element filled with errors

This is needed for proper styling, take for example the bootstrap ones (https://getbootstrap.com/docs/4.4/components/forms/#validation):

### Before submit

![immagine](https://user-images.githubusercontent.com/152236/78237475-a9951100-74db-11ea-887e-309117b9d6c8.png)

### After submit

![immagine](https://user-images.githubusercontent.com/152236/78237503-b3b70f80-74db-11ea-9d73-61c51a036297.png)

With the current release, the valid fields cannot be styled to be green, as far as I can tell.

**Comment by froschdesign** [comment]
@Slamdunk 
_First, sorry for the very late response._

> With the current release, the valid fields cannot be styled to be green, as far as I can tell.

Right, only class for inputs with errors can be added:

```php
$this->formRow()->setInputErrorClass('is-invalid');
```

https://github.com/laminas/laminas-form/blob/bd58a31aab023f722eed1b6b9a073fafafd62c8c/src/View/Helper/FormRow.php#L148-L154

Do you have a suggestion for valid elements?

**Comment by Slamdunk** [comment]
The question is: how can I know whether an element is "filled" or not?
The answer is tricky, because `null` or empty string could be valid "filled" states.
I think this FR requires a change into the `ElementInterface` that tells when, for example, `setValue` was called or not.

WDYT?

**Comment by froschdesign** [comment]
> I think this FR requires a change into the `ElementInterface` that tells when, for example, `setValue` was called or not.

You mean a method and property like `hasValue`:

```php
public function hasValue()
{
    return $this->hasValue;
}

public function getValue()
{
    return $this->hasValue ? $this->value : null;
}
```

But maybe we can find a solution without a BC break which means no change at the interface and same behaviour (no change in `Laminas\Form\Element::getValue()`).

**Comment by Slamdunk** [comment]
No BC break required:
```php
private $hasValue = false;

public function setValue($value)
{
    $this->value = $value;
    $this->hasValue = true;
    return $this;
}

public function hasValue()
{
    return $this->hasValue;
}

public function getValue()
{
    return $this->value;
}
```

**Comment by froschdesign** [comment]
@Slamdunk 
Would you create a pull request for your suggestion?

**Comment by ALTAMASH80** [comment]
Hi, If the above code has not been added yet, I can add it and mention @SlamDunk. Thanks!

**Comment by Slamdunk** [comment]
Sorry, I've forgotten this one.
Yes please, if you can PR this it would be great 👍

**Comment by ALTAMASH80** [comment]
Hi @Slamdunk, my PR has a cross on it. I've no idea why. But added the code is present in the comment section. Thanks!
