### ISSUE TITLE
[RFC: PHP 8 Support] Replace Form Annotations with PHP 8 Attributes

### ISSUE THREAD

**Issue by charma** [laminas/laminas-form#84]
As of current ongoing PHP8-discussions and Pull Requests regarding support for Form Annotations I suggest:
How about using the natively supported introduced PHP Attributes https://www.php.net/manual/de/language.attributes.overview.php from PHP 8 instead?

**Comment by froschdesign** [comment]
@charma 
> …was dropped completly without replacement.

That is not true. Nothing is removed. Such statements are not helpful while a solution is being worked on!

Please change the title and the text, otherwise we will have to close this issue report as invalid. Thanks!

**Comment by charma** [comment]
changed as suggested. hope thats acceptable now

**Comment by froschdesign** [comment]
A replacement means that PHP 7 support is cut off and we need a migration tool. The last is good, but cutting off support for PHP 7?

This would work, but needs a new major version.

**Comment by charma** [comment]
yes, this would not be backwards-compatible. But the composer-dependencies for other php8-compatible versions are not backwards-compatible either (e.g. laminas-code) so the php8-supporting version will not be backwards compatible to previous versions anyway.

**Comment by froschdesign** [comment]
@charma 
Are you willing to help here? Can you work out a concrete concept for this?

**Comment by charma** [comment]
@froschdesign sure, y not. I can give it a try, but it'll take a while until I can get to it.
To what extend do you need the concept? Is a text description enough or do you need a draft/prototype implementation?

**Comment by driehle** [comment]
I have added a proposal for an implementation in MR #113

**Comment by Slamdunk** [comment]
Closed by #113
